--- #YAML:1.0
name:                Megagram-ResolveSRV
version:             0.01
abstract:            ~
license:             ~
author:              
    - Dusty Wilson <dusty@megagram.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Net::DNS:                      0.01
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
